# DAT 19: Homework 3 Assignment - Clustering with K-means

## Instructions

In this homework assignment, we will get practice with our first unsupervised learning technique, clustering. We will analyze wholesale purchases by 440 clients of a wholesale distributor. 

Please do all your analysis to answer the questions below in this Jupyter notebook. Show your work.

**Please submit your completed notebook by 6:30PM on Wednesday, January 20.**

## About the Data

The [Wholesale Customers dataset](http://archive.ics.uci.edu/ml/datasets/Wholesale+customers) and a description of the data is available from the UCI ML Repository.

## Homework Assignment

**1) Load the dataset. Check for missing values, perform any normalization that you think is necessary (remember that K-means uses the Euclidean Distance function).**

In [1]:
import numpy as np
import pandas as pd
import csv as csv

sale = pd.read_csv('Wholesale.csv', header=0)
print(sale)

     Channel  Region  Fresh   Milk  Grocery  Frozen  Detergents_Paper  \
0          2       3  12669   9656     7561     214              2674   
1          2       3   7057   9810     9568    1762              3293   
2          2       3   6353   8808     7684    2405              3516   
3          1       3  13265   1196     4221    6404               507   
4          2       3  22615   5410     7198    3915              1777   
5          2       3   9413   8259     5126     666              1795   
6          2       3  12126   3199     6975     480              3140   
7          2       3   7579   4956     9426    1669              3321   
8          1       3   5963   3648     6192     425              1716   
9          2       3   6006  11093    18881    1159              7425   
10         2       3   3366   5403    12974    4400              5977   
11         2       3  13146   1124     4523    1420               549   
12         2       3  31714  12319    11757     287

**2.1) Look at the dataset. There are both continuous and categorical variables. What are the categorical variables? From a business perspective, what do those categorical variables represent?**

In [2]:
#Categorical variables are Channel and Region. They represent the buckets/clusters in which the continuous variables (Fresh, Milk, Grocery, Frozen, Detergents_Paper, Delicassen) are measured.

**2.2) What results might we expect from the k-means clustering if we were to run it on the dataset as-is? Explain your thinking in words.**

In [ ]:
#If we were to run the dataset as is, I would guess there would be just a few clusters, maybe 3. That is because even though the datapoints are  so spread out, one of the smallest values is '3', and largest '43088', the number of datapoints is so big (440) that they can be grouped in just a few clusters.

**3) Using ONLY the continuous features in the dataset, apply the K-means algorithm to find clusters in the data.**

In [3]:
from sklearn.cluster import KMeans
from bokeh.plotting import figure,show,output_notebook

X = sale[['Region', 'Fresh', 'Frozen']]
print(X)

     Region  Fresh  Frozen
0         3  12669     214
1         3   7057    1762
2         3   6353    2405
3         3  13265    6404
4         3  22615    3915
5         3   9413     666
6         3  12126     480
7         3   7579    1669
8         3   5963     425
9         3   6006    1159
10        3   3366    4400
11        3  13146    1420
12        3  31714     287
13        3  21217    3095
14        3  24653     294
15        3  10253     397
16        3   1020     134
17        3   5876     839
18        3  18601    2205
19        3   7780     669
20        3  17546    1066
21        3   5567    3383
22        3  31276    9408
23        3  26373    5154
24        3  22647    2915
25        3  16165     201
26        3   9898    3151
27        3  14276     485
28        3   4113    1158
29        3  43088    1200
..      ...    ...     ...
410       3   6633    1389
411       3   2126    1535
412       3     97      98
413       3   4983   17866
414       3   5969    5679
4

In [4]:
km = KMeans(3)
km.fit(X)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=3, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=None, tol=0.0001,
    verbose=0)

**4.1) Plot the Silhouette Coefficient as a function of the number of clusters (remember that you set the number of clusters as an input to K-means).**

In [5]:
centers = km.cluster_centers_
print(centers)

[[  2.51194539e+00   5.31520137e+03   2.20515358e+03]
 [  2.57851240e+00   2.04273719e+04   3.86278512e+03]
 [  2.73076923e+00   4.81178846e+04   9.15934615e+03]]


In [6]:
colors = list()
target = X['Region']
color_mapping = {1:'red',2:'blue',3:'orange'}

In [11]:
for value in target:
    new_color = color_mapping[value]
    colors.append(new_color)
print(colors)

cluster_1 = X['Frozen']
cluster_2 = X['Fresh']

['orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange',

In [8]:
p = figure(title='Clusters in Whole Sales', tools='')
p.circle(x=cluster_1, y=cluster_2, size=5, color=colors)
p.circle(x=centers[:,0], y=centers[:,1], alpha=0.4, color='green', size=100)
show(p)

In [12]:
manykm = KMeans(10)
manykm.fit(X)
manycenters = manykm.cluster_centers_

In [13]:
q = figure(title='Clusters in Whole Sales', tools='')
q.circle(x=cluster_1, y=cluster_2, size=5, color=colors)
q.circle(x=centers[:,0], y=centers[:,1], alpha=0.4, color='green', size=100)
show(q)

In [14]:
from sklearn.metrics import silhouette_score
labels = km.labels_
label_euclidean_score = silhouette_score(X,labels,metric='euclidean')
print(label_euclidean_score)

0.553415664765


In [15]:
manylabels = manykm.labels_
manylabels_euclidean_score = silhouette_score(X,manylabels,metric='euclidean')
print(manylabels_euclidean_score)

0.415412794987


/Users/IlmaKhan/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)


**4.2) What is the ideal value for k, the number of clusters? Why?**

In [3]:
#5 looks like a good number of clusters to have in this dataset because our silhouette score is 0.55.

**4.3) How does your answer for 3.2 compare with your thoughts from 2.2 above?**

In [ ]:
#Well I was wrong- we actually have 5 clusters instead of, my guess, 3.

### Extra Credit Questions
**The following questions are strongly encouraged, but not required for this homework assignment.**

**5) Read the scikit-learn user guide section about [clustering](http://scikit-learn.org/stable/modules/clustering.html). Pay particular attention to the section about [assumptions](http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_assumptions.html#example-cluster-plot-kmeans-assumptions-py).**

**6) PCA & PLOTTING:** <br> With six continuous features, plotting our clusters in two dimensions will be challenging. We can use [Principal Components Analysis](http://scikit-learn.org/stable/modules/decomposition.html#pca) and then plot only the "top two" dimensions. More technically, these are the dimensions that capture most of the variance in our data set. For this extra credit question, read about [PCA in the sklearn.decomposition module](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html), apply it to the wholesale dataset, repeat the k-means clustering, and plot your results using only the top two principal components.

In [4]:
#your code here, should you choose to attempt it